[book]

title = "Vulkan Tutorial (Rust)"
authors = ["Kyle Mayes"]

language = "en"
multilingual = false

src = "src"

edition = "edition2018"

[output.html]

git-repository-url = "https://github.com/KyleMayes/vulkanalia"
