[package]

edition = "2018"

name = "vulkanalia"
authors = ["Kyle Mayes <kyle@mayeses.com>"]

version = "0.1.0"

readme = "../README.md"
license = "Apache-2.0"

description = "Vulkan bindings for Rust."

documentation = "https://docs.rs/vulkanalia"
repository = "https://github.com/KyleMayes/vulkanalia"
