name: Update

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:
    inputs: {}

jobs:

  update-bindings:
    name: Update - Bindings
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Dependencies
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
      # Update
      - name: Update Bindings
        working-directory: ./generator
        run: |
          ./gradlew run --args="\
            --directory=.. \
            --username=KyleMayes \
            --token=${{ secrets.PERSONAL_ACCESS_TOKEN }} \
            update \
            --repo=${{ github.repository }}"
